"""empty message

Revision ID: 0e5312d2b2e5
Revises: 1b3fa53a04d1
Create Date: 2024-01-08 13:07:09.042695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5312d2b2e5'
down_revision = '1b3fa53a04d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('ad_subcategory', 'sub_category', ['sub_category_id'], ['id'])
        batch_op.drop_column('category_id')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('ad_subcategory', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
