"""empty message

Revision ID: 3f1384c22963
Revises: 48c942d219f0
Create Date: 2023-12-06 09:54:40.993408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1384c22963'
down_revision = '48c942d219f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_empresa', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
