"""empty message

Revision ID: 49c304b87f2d
Revises: 31a372cc58ac
Create Date: 2023-12-05 14:33:14.558625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c304b87f2d'
down_revision = '31a372cc58ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_info', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_person', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('state_registration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('address')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('state_registration')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('cpf')
        batch_op.drop_column('is_person')
        batch_op.drop_column('is_complete')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status_info')

    # ### end Alembic commands ###
