"""empty message

Revision ID: 4e4d857f4aab
Revises: 0e5312d2b2e5
Create Date: 2024-01-08 13:58:28.272468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4d857f4aab'
down_revision = '0e5312d2b2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ad_subcategory', 'sub_category', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ad_subcategory', type_='foreignkey')

    # ### end Alembic commands ###
