"""empty message

Revision ID: 898a0c6cdc39
Revises: 51c391b0be58
Create Date: 2023-12-05 15:13:19.627067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898a0c6cdc39'
down_revision = '51c391b0be58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
